### ISSUE TITLE
Use AJAX to load the toc file

### ISSUE THREAD

**Issue by ricksbrown** [peakcontent/nothingCMS#3]
Currently the toc file is loaded using an iframe. This is likely to cause issues at some point in some browser.

An XHR (AJAX) would be the standard way to load something like this.
See: https://developer.mozilla.org/en-US/docs/AJAX/Getting_Started

**Comment by peakcontent** [comment]
Done. Though at this point iFrame functionality is still central to the script as it allows for the easy display of a range of content.
